---
- name: setup netdata
  import_tasks: netdata.yml
  become: true
  when: srv_netdata_enable |bool
  tags: srv_netdata_all

- name: install monitoring tools
  apt:
    name: "{{ srv_netdata_tools_packages }}"
  become: true
  when: srv_netdata_tools |bool
  tags: srv_netdata_tools

- name: setup haveged (entropy daemon)
  import_tasks: entropy.yml
  become: true
  when: srv_netdata_entropy |bool
  tags: [srv_netdata_entropy, srv_netdata_haveged]

- name: install sysdig
  import_tasks: sysdig.yml
  become: true
  when: srv_netdata_sysdig |bool
  tags: srv_netdata_sysdig

- name: install cockpit
  import_tasks: cockpit.yml
  become: true
  when: srv_netdata_cockpit |bool
  tags: srv_netdata_cockpit

- name: apply postponed changes now
  meta: flush_handlers
  tags: srv_netdata_all
...
