---
# handlers for ivansible.srv_netdata

- name: restart netdata service
  systemd:
    name: netdata
    state: restarted
    enabled: true
  become: true

- name: reload netdata alarms
  command: killall -USR2 netdata
  become: true
...
